name: jim
description: "A new Flutter project."
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.3.4 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  get: ^4.7.2
  flutter_native_splash: ^2.4.0
  curved_navigation_bar: ^1.0.3
  flutter_screenutil: ^5.9.3
  google_fonts: ^6.2.1
  flutter_svg: ^2.0.10+1
  firebase_core: ^3.11.0
  cloud_firestore: ^5.6.3
  cached_network_image: ^3.4.1
  carousel_slider: ^4.2.1
  firebase_auth: ^5.5.0
  hive_flutter: ^1.1.0
  hive: ^2.2.3
  fl_chart: ^0.63.0
  intl: ^0.20.2
  lottie: ^3.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/anatomy/
    - assets/images/
    - assets/animations/
    - assets/fonts/
  fonts:
    - family: PlusJakartaSans
      fonts:
        - asset: assets/fonts/PlusJakartaSans-Regular.ttf
        - asset: assets/fonts/PlusJakartaSans-Medium.ttf
          weight: 500
        - asset: assets/fonts/PlusJakartaSans-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/PlusJakartaSans-Bold.ttf
          weight: 700

flutter_native_splash:
  color: "#121418"
  image: "assets/images/splash_logo.png" # Rename your optimized image to splash_logo.png
  android: true
  ios: true
  fullscreen: true
  android_12:
    image: "assets/images/splash_logo.png"
    icon_background_color: "#121418"
  android_gravity: center
  ios_content_mode: center
  web: false
